CESNET/ipfixprobe

packet.h, pcapreader.cpp
Fixed bug in payload length computation. Padding bytes were included in the length.
=> fixed payload length computation for frames shorter than 64 bytes

idpcontentplugin.cpp, idpcontentplugin.h, pstatsplugin.cpp, pstatsplugin.h
Fixed export of `pstats` and `idpcontent` plugins.
Problem was that parsing and data saving should been done in `post_update` instead of `pre_update` for general plugin (other protocol specific plugins could flushed and reinserted packet, thus exported data are duplicated).
=> Plugin export fix

Makefile.am, byte-utils.h, ipfix-basiclist.cpp, ipfix-basiclist.h, pstatsplugin.h
The `IpfixBasicList` class makes basic list export much easier. It literally creates the basic list structure with only one method and moves it to the c-style buffer
=> Adding New Feature: Easier creation of IPFIX BasicList Structure with `IpfixBasicList` class

init/ipfixprobed, init/link0.conf.example
Configuration file now allows to declare IFCLIST array to specify
multiple instances of `-I` argument.
The example was added into link0.conf.example
=> ipfixprobed: extend service to support list of interfaces

Makefile.am, configure.ac, include/ipfixprobe/ipfix-elements.hpp, input/dpdk.cpp, input/dpdk.h, input/stem.cpp, input/stem.hpp, ipfixprobe.cpp, process/flexprobe-data-processing.cpp, process/flexprobe-data-processing.h, process/flexprobe-data.h, process/flexprobe-encryption-processing.cpp, process/flexprobe-encryption-processing.h, process/flexprobe-tcp-tracking.cpp, process/flexprobe-tcp-tracking.h
Branch implements DPDK interface support for ipfixprobe. This will allow for running the probe with any DPDK-supported NIC. Branch also adds support for FlexProbe HW accelerated probe for monitoring network traffic.
=> Dpdk flexprobe extension

storage/cache.cpp, storage/cache.hpp
EOF reason  is exported instead of the inactive timeout when TCP FIN or TCP RST flag is set
=> FIXED export reason

input/dpdk.cpp, input/dpdk.h
Update for DPDK interface
Fixes an issue with double-free on used mbufs and adds version check for MTU settings since these changed with new version of DPDK.
=> Dpdk ifc update

include/ipfixprobe/ipfix-elements.hpp, process/flexprobe-data-processing.cpp, process/flexprobe-data-processing.h
Default input interface item is sourced from a field that doesn't match the information needed by Flexprobe.
=> Added InterfaceIn for Flexprobe data

process/quic_parser.cpp, process/tls_parser.cpp, process/tls_parser.hpp
OpenWrt build failed due to unknown uint type and missing include of <endian.h> in QUIC / TLS code.
=> tls: BUGFIX replaced unknown uint with size_t, add missing header file

Makefile.am
added -fPIC compiler flag to solve issue in Turris build reported by
@BKPepe in https://github.com/CESNET/Nemea-OpenWRT/issues/36
=> build: BUGFIX dangerous relocation

process/http.cpp
Fields exported by the HTTP plugin sometimes had '\r' at the end. This PR removes trailing '\r' from exported fields.
=> BUGFIX: Removed trailing '\r' from HTTP exported fields

input/dpdk.cpp, input/dpdk.h
Skip RSS setting or HW timestamps when they are not supported by
hardware of ipfixprobe.
This PR fixes the use in virtual machine with uio_pci_generic driver.
It was tested with Ubuntu jammy in VirtualBox.
=> dpdk: check capabilities and skip unsupported features

README.md
Based on feedback from #81, it was not very clear what is the output of ipfixprobe when some output plugin is used.
The aim of this patch is to make the readme file more general - if a user enables some processing plugin (by `-p`), there are extended fields included in the output flow records. It works for `unirec`, `ipfix`, or `text` plugins.
=> Improved description of output

process/pstats.cpp
The pstats plugin badly recognized zero-len packets and did not export correctly data for pcaps with stripped payload.
=> PSTATS BUGFIX: Fixed zero-len packets recognition

Makefile.am, README.md, input/dpdk-ring.cpp, input/dpdk-ring.h
Added a new input plugin, `dpdk-ring`, which enables ipfixprobe reading from shared memory as a consumer so that ipfixprobe can play the role of DPDK secondary process. See Examples in README.md for checking mandatory parameters.
=> DPDK ring reader

init/Makefile.am, init/dpdk_direct.conf.example, init/dpdk_mring.conf.example, init/ipfixprobed, init/link0.conf.example, ipfixprobe.spec.in
The description of new variables was added into link0.conf.example:
DPDK_RING, DPDK_RING_PATTERN, DPDK_RING_STARTIDX
also, there is new DPDK_OPTS variable to set mem and mbuf.
There are new examples dpdk_direct.conf.example and
dpdk_mring.conf.example.
=> dpdk: propose new variables to control init by ipfixprobed

include/ipfixprobe/packet.hpp, include/ipfixprobe/rtp.hpp, include/ipfixprobe/utils.hpp
The missing `#include <sys/time.h>` directives caused build failure on OpenWrt.
=> openwrt: add missing include of time.h

Makefile.am, docker/Dockerfile, docker/README.md, docker/ipfixprobe_wrapper.sh, docker/process_script.sh
This PR adds a docker/podman setup for running ipfixprobe to export pcap files to csv. It includes:
1. Dockerfile that installs all necessary dependencies.
2. Wrapper script to build image if necessary, run ipfixprobe inside the container, handling input and output files.
3. A (example) processing script that uses ipfixprobe and nemea to generate CSV logs from pcap data.
4. Readme with doc
Usage:
1. Build the Docker image: docker build -t docker_ipfixprobe .
2. Run the export: ./ipfixprobe_wrapper.sh <process_script.sh> <input_file.pcap> <output_file.csv>
=> docker - introduce docker container for processing pcaps to csvs

ChangeLog, NEWS, configure.ac
Bump to version 4.12.0
Changelog:
* ipfix plugin: support lz4 compression
* ipfixprobe: possibility to set workers affinity
* parser: fix ipv6 extension header parsing
* telemetry: supports telemetry over appFs
* build: c++ standard gnu++17
* dpdk: set mtu, fixes
* mqtt: new process plugin
* tls plugin: fix, extract more flow details
* ndp: support new firmware timestamps
* flowcache: introduce fragmentation cache
* QUIC: refactor, extract more flow details
=> ipfixprobe: increased version, updated ChangeLog, released RPM package

input/dpdk.h, input/dpdk/dpdkDevice.cpp, input/dpdk/dpdkDevice.hpp
Ipfixprobe with DpdkDevice plugin used burst size as number of descriptors in rx queue between HW and SW. It was too small number and traffic was dropped. Now plugin uses the same size for mempool and number of descriptors. Default size of mempool was decreased to standard 4096 mbufs. Default burst size remains at 64 mbufs.
=> Dpdk rx queue size fix

docs/_config.yml, docs/_sass/footer.scss
- Fixed jekyll base url to prevent 404 errors
- Fixed centering in the footer
=> Minor fixes in doc webpage

include/ipfixprobe/ipfix-elements.hpp
Use standard conversion to ntp timestamps as in https://tickelton.gitlab.io/articles/ntp-timestamps/.
=> ipfix-elements: fix NTP_USEC_TO_FRAC macro

Makefile.am, input/dpdk/dpdkCompat.hpp, input/dpdk/dpdkDevice.cpp, input/dpdk/dpdkDevice.hpp
Previously, RSS was set to RTE_ETH_RSS_IP, which is not supported by all NICs. This update allows configuring RSS to a subset of RTE_ETH_RSS_IP, ensuring better compatibility.
=> dpdk: fix RSS configuration

input/dpdk.h, input/dpdk/dpdkDevice.cpp
=> Dpdk - set RX queue size as (mempool size / 2)

input/parser.cpp
Ensure correct packet parsing for input modules like dpdk, dpdk-ring, and nfb when compiled with --with-pcap. Previously, the parser relied on opt->datalink, which these inputs do not set, leading to incorrect layer detection. Now, it correctly defaults to Ethernet when necessary.
Solve #251
=> Parser - Fix packet parsing issue when --with-pcap is enabled

pkg/rpm/ipfixprobe-msec.spec.in, pkg/rpm/ipfixprobe-nemea.spec.in, pkg/rpm/ipfixprobe.spec.in
Update `ipfixprobe.spec.in`, `ipfixprobe-msec.spec.in` and `ipfixprobe-nemea.spec.in`
=> Update RPM spec files

.github/workflows/copr-upload.yml
Upload srpm files to copr (ipfixprobe-testing) on push to branch release.
Upload srpm files to copr (ipfixprobe) on push to branch stable.
=> Github-actions: add copr-upload workflow

src/plugins/process/basicplus/CMakeLists.txt, src/plugins/process/bstats/CMakeLists.txt, src/plugins/process/dns/CMakeLists.txt, src/plugins/process/dnssd/CMakeLists.txt, src/plugins/process/flowHash/CMakeLists.txt, src/plugins/process/http/CMakeLists.txt, src/plugins/process/icmp/CMakeLists.txt, src/plugins/process/idpContent/CMakeLists.txt, src/plugins/process/mpls/CMakeLists.txt, src/plugins/process/mqtt/CMakeLists.txt, src/plugins/process/netbios/CMakeLists.txt, src/plugins/process/nettisa/CMakeLists.txt, src/plugins/process/ntp/CMakeLists.txt, src/plugins/process/osquery/CMakeLists.txt, src/plugins/process/ovpn/CMakeLists.txt, src/plugins/process/passiveDns/CMakeLists.txt, src/plugins/process/phists/CMakeLists.txt, src/plugins/process/pstats/CMakeLists.txt, src/plugins/process/quic/CMakeLists.txt, src/plugins/process/rtsp/CMakeLists.txt, src/plugins/process/sip/CMakeLists.txt, src/plugins/process/smtp/CMakeLists.txt, src/plugins/process/ssaDetector/CMakeLists.txt, src/plugins/process/ssdp/CMakeLists.txt, src/plugins/process/tls/CMakeLists.txt, src/plugins/process/vlan/CMakeLists.txt, src/plugins/process/wg/CMakeLists.txt
Add missing libtrap library to CMakeLists for all process plugins
=> ipfixprobe-nemea: Add dependency on libtrap library

src/plugins/process/flowHash/src/flow_hash.cpp, src/plugins/process/flowHash/src/flow_hash.hpp
This is done to unify the names of all process plugins
=> FlowHash: Rename flow_hash process plugin to flowhash

src/plugins/input/dpdk/src/dpdkDevice.cpp
Fixes issues related to incorrect MTU handling and associated mbuf allocation failures.
=> Dpdk: Add DPDK mbuf alignment to max_packet_size calculation

init/config2args.py
Fix queue size and workers affinity for DPDK
Script is now compatible with python3.6
=> ipfixprobed: fix config2args

src/core/ipfixprobe.cpp
Handle SIGABRT alongside SIGSEGV to improve diagnostic capabilities during abnormal termination, especially when triggered by libunwind, sanitizers, or runtime assertions.
This PR updates the signal handling mechanism to treat SIGABRT similarly to SIGSEGV.
When the application receives SIGABRT (e.g. due to abort(), failed assert(), or sanitizers), it now properly invokes st_dump() to capture diagnostic output.
The handler then exits using exit(EXIT_FAILURE) instead of abort() to prevent recursive signal triggering.
This ensures that crashes triggered by internal runtime mechanisms (like libunwind, ASan, or failed invariants) are logged consistently.
---
~- [ ] Documentation (e.g. Doxygen) is updated if needed~
~- [ ] Relevant documentation was updated (if needed)~
---
=> ipfixprobe.cpp: handle SIGABRT to support libunwind-based diagnostics

src/plugins/input/nfb/src/ndpReader.cpp
Replace numa_bind with numa_set_preferred for flexible memory allocation
Switched from `numa_bind()` to `numa_set_preferred()` with `numa_set_bind_policy(0)` to allow preferred NUMA node memory allocation without hard binding. This enables memory to be allocated on the preferred NUMA node first, but allows fallback to others when necessary.
---
~- [ ] Relevant documentation was updated (if needed)~
~- [ ] Documentation (e.g. Doxygen) is updated if needed~
---
=> NfbPlugin: use NUMA preferred policy instead of strict binding

src/plugins/input/nfb/src/ndpReader.cpp
Log a warning instead of returning an error when NUMA node detection fails.
Previously, failing to detect a NUMA node caused the function to return an error and abort execution.  
Now, the code prints a warning to stderr and continues running, allowing the program to operate without NUMA preference.  
---
---
=> NfbPlugin: log warning instead of exiting on NUMA node detection failure

init/config2args.py
Fix incorrect quoting when building raw interface parameter strings in **config2args.py**.
Previously the closing quote was on incorrect place.
If configuration file contains _block_count_ or _packets_in_block_ parameters, the final string contains unquoted **;**. The final string then is **ipfixprobe -i "raw;ifc=eth0";blocks=2048 ...** and rest of the command is ignored.
---
---
=> Fix raw interface parameters quoting

src/plugins/process/quic/src/quic.cpp
Fix add_quic() function invalid return code that caused pipeline infinite loop
Fix invalid return code in add_quic() that caused possibility the processing pipeline to enter an infinite loop. 
The function previously returned internal QUIC status codes that were not properly handled by the pipeline.
---
- ~~[ ] Relevant documentation was updated (if needed)~~
- ~~[ ] Documentation (e.g. Doxygen) is updated if needed~~
---
=> Process - Quic - fix invalid return code from add_quic()
